version: "3.2"
services:

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - /media/alex/HDD_STORAGE/redis/data:/var/lib/redis

    environment:
      - REDIS_REPLICATION_MODE=master